- display: "Dataset__name of single-cell dataset record"
  ui_component: "magma-record"
  doc: "Provide the identifier ('name' attribute) of the sc_seq_dataset record you wish to explore here. Note that we definitely plan to improve this particular selection method in the future!"
  input:
    preset:
      modelName: 'sc_seq_dataset'
      targetAtt: 'name'
      otherAttsShow: ['group_id', 'description']
      hasAtts: ['seurat_object']
  output:
    params: [ "dataset_name" ]
- display: "Set plot options"
  name: 'plot_setup_ui'
  ui_component: "any-dittoseq"
  doc: "Options here determine both what type of plot to make, and how to set that plot up. For addtional details on individual inputs, see the 'Inputs of the Plot Configuration Interface' section of Vulcan's 'Help'-page documentation OR dittoSeq's own documentation. Any inputs without an exact label match within that Vulcan 'Help'-page table will map directly to some dittoSeq input for the function with the same name as your chosen plot type. You can find dittoSeq's documentation from either within R itself, run `?dittoSeq::<visualization-name>`, or from the RDRR.io page that pops up when you google the package."
  input:
    files:
      data_frame: "discrete_metadata_summary.json"
      continuous_opts: "continuous_opts.json"
      discrete_opts: "discrete_opts.json"
      all_opts: "all_opts.json"
      reduction_opts: "reduction_opts.json"
  output:
    files: [ plot_setup.json ]
- display: "Display Plot"
  ui_component: "plot"
  input:
    files: [ "plot.out" ]
